version: 2.1

orbs:
  ruby: circleci/ruby@1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
  test:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: '1.17.2'
          with-cache: false
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build